# Generated by Django 3.1.4 on 2021-04-26 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('YT', 'Youtube'), ('Goog', 'Google'), ('NewsLetter', 'NewsLetter')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='special_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
